apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-evidence-collector
  labels:
    app.kubernetes.io/name: evidence-collector
    app.kubernetes.io/managed-by: {{ .Release.Service }}
